jobs:
  integration-delivery:
    runs-on: ubuntu-latest
    environment: Test
    container:
      image: node
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: Install TestCafe
        run: npm install -g testcafe

      - name: Update APT
        run: apt-get update

      - name: Install Chromium
        run: apt-get install -y chromium

      - name: Run tests
        run: testcafe chromium:headless test/*

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/
